version: '3'

services:
 frontend:
  build: ./frontend
  ports:
   - '3000:3000'
  volumes:
   - /usr/app/node_modules
   - ./frontend:/usr/app
  depends_on:
   - 'backend'
  command: ./wait-for-it.sh backend:3333 -t 0 -- yarn dev
  networks:
   - fullstack-app

 backend:
  build: ./backend
  ports:
   - '3333:3333'
  volumes:
   - /usr/app/node_modules
   - ./backend:/usr/app
  depends_on:
   - 'mysql'
  command: ./wait-for-it.sh mysql:3306 -t 0 -- yarn dev
  networks:
   - fullstack-app

 mysql:
  image: mysql
  ports:
   - '3306:3306'
  environment:
   - MYSQL_ROOT_PASSWORD=admin
   - MYSQL_DATABASE=4events
   - MYSQL_USER=admin
   - MYSQL_PASSWORD=admin
  networks:
   - fullstack-app

networks:
 fullstack-app:
  driver: bridge
